### PR TITLE
Add variable for certbot version

### PR DESCRIPTION
**Pull request by fapdash**

### CODE REVIEW

**Review by enricostano — APPROVED** [review]
Many thanks @fapdash !

**Comment by enricostano** [comment]
I'm thinking about setting up CI before merging this, just to give it a try.

Unless this is urgent @fapdash , we can plan a release with latest changes ASAP.

**Comment by enricostano** [comment]
@fapdash https://github.com/coopdevs/certbot_nginx/pull/16 what do you think?

**Comment by fapdash** [comment]
@enricostano https://github.com/coopdevs/certbot_nginx/pull/16 looks great, just keep in mind that it currently only tests the installation, not the certificate creation.
I've rebased this PR to remove merge conflicts.

**Review by danypr92 — COMMENTED** [review]
:clap: Great job!

**Review by danypr92 — APPROVED** [review]

**Comment by enricostano** [comment]
@fapdash I merged #16 , if you don't mind let's rebase again this branch to see it working.

Many thanks for your contributions! :muscle:

**Pull request merged**
